openapi: "3.0.2"
info:
  title: "Sample API"
  version: "1.0.0"
servers:
  - url: http://localhost:8080/
paths:
  /users:
    get:
      summary: "Get list of users"
      operationId: "getUsers"
      responses:
        "200":
          description: "A list of users"
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        status:
                          type: string