# データベース用のDockerfile
FROM postgres:14-alpine3.20

# 必要な環境変数を設定
ENV POSTGRES_USER="me"
ENV POSTGRES_DB="development"
ENV POSTGRES_HOST_AUTH_METHOD="trust"

# 必要に応じて初期化スクリプトや設定を追加
COPY ./db/init /docker-entrypoint-initdb.d/
