version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://me@db:5432/development?sslmode=disable
      - PORT=8080
  
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: me
      POSTGRES_DB: development
      POSTGRES_HOST_AUTH_METHOD: trust # パスワードなしで接続許可（非推奨）
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/postgresql/data

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /api/api-document.yaml
    volumes:
      - ./api-document.yaml:/api/api-document.yaml:ro
    ports:
      - "127.0.0.1:8000:8000"

volumes:
  db-data: